// Nexus service worker — offline-first without stale application code.
const CACHE='cert-tracker-assets-v4.32.2-autonomous-v20';
const CORE_ASSETS=[
  './assets/nexus-template-one-reference.jpg',
  './','./index.html','./styles.css','./professional.css','./professional-components.css','./learning-resources.css','./roadmap-map.css','./roadmap-zoom.css','./professional-overrides.css','./professional-depth.css','./professional-symbols.css','./professional-typography.css','./responsive-layout.css','./browser-compat.css','./mobile-navigation.css','./today-recommendations.css','./notification-center.css','./platform-alignment.css','./career-advisor.css','./career-mentor.css','./weekly-coach.css','./mobile-polish.css','./template-one.css','./nexus-template-one.css','./nexus-template-one-exact.css','./nexus-template-one-cleanup.css','./autonomous-assistant.css',
  './assets/hud/app-icon-192.png','./assets/hud/app-icon-512.png','./assets/hud/pathway-emblems.svg','./assets/hud/tier-bronze.png','./assets/hud/tier-silver.png','./assets/hud/tier-gold.png','./assets/hud/tier-platinum.png','./assets/hud/tier-diamond.png','./assets/hud/knowledge-core.png','./assets/hud/career-core.png','./assets/hud/gateway-core.png','./assets/hud/completed-core.png','./assets/hud/progress-core.png','./assets/hud/critical-core.png','./assets/hud/analytics.png','./assets/hud/roadmap.png','./assets/hud/network.png','./assets/hud/certifications.png','./assets/hud/strategy.png','./assets/hud/customize.png','./assets/hud/learning.png','./assets/hud/tutor.png','./assets/hud/resources.png','./assets/hud/play.png','./assets/hud/external.png','./assets/hud/filter.png','./assets/hud/search.png','./assets/hud/calendar.png','./assets/hud/alerts.png','./assets/hud/sync.png','./assets/hud/refresh.png','./assets/hud/expand.png','./assets/hud/collapse.png','./assets/hud/dock.png','./assets/hud/next.png','./assets/hud/complete.png','./assets/hud/progress.png','./assets/hud/privacy.png','./assets/hud/global.png',
  './certs.js','./src/browser-compat.js','./src/security-hardening.js','./src/responsive-layout.js','./src/cert-extensions.js','./src/catalogue-currentness.js','./src/catalogue-policy-normalize.js','./src/path-defaults.js','./src/career-path-v14.js','./src/config.js','./src/curriculum-audit.js','./src/learning-resources.js','./src/learning-resources-normalize.js','./src/state-core.js','./src/renderer.js','./src/dates.js','./src/storage.js','./src/personalization.js','./src/validation.js','./src/phase-engine.js','./src/source-registry.js','./src/source-registry-current.js','./src/data-health.js','./src/competency-engine.js','./src/market-value.js','./src/career-framework.js','./src/career-context-v14.js','./src/capability-gates.js','./src/recommendation-engine.js','./src/filter-intelligence.js','./src/dual-pillar-depth.js','./src/market-readiness.js','./src/role-readiness-rank.js','./src/filter-goal-model.js','./src/job-market.js','./src/career-options.js','./src/career-think-tank.js','./src/topic-engine.js','./src/planner.js','./src/career-advisor.js','./src/assessment-bank.js','./src/career-mentor.js','./src/weekly-coach.js','./src/exports.js','./src/notifications.js','./src/sync.js','./src/github-sync.js','./src/account-connections.js','./src/personal-intelligence.js','./src/intelligence-nextgen.js','./src/intelligence-strategy.js','./src/ux.js','./src/github-sync-ui.js','./src/account-connections-ui.js','./src/market-value-ui.js','./src/intelligence-ui.js','./src/career-ui.js','./src/learning-path-ui.js','./src/roadmap-zoom.js','./src/roadmap-map-ui.js','./src/roadmap-clickthrough.js','./src/personalization-ui.js','./src/workspace-shell.js','./src/outlook-intelligence-ui.js','./src/personal-intelligence-ui.js','./src/intelligence-nextgen-ui.js','./src/intelligence-strategy-ui.js','./src/autonomous-assistant.js','./src/career-options-ui.js','./src/learning-resources-ui.js','./src/dual-pillar-ui.js','./src/market-dashboard-ui.js','./src/market-profile-ui.js','./src/career-advisor-ui.js','./src/career-mentor-ui.js','./src/weekly-coach-ui.js','./src/role-readiness-ui.js','./src/depth-ui.js','./src/professional-icons.js','./src/role-icons-render.js','./src/accessibility.js','./src/notification-center-ui.js','./src/bootstrap.js','./src/nexus-theme.js','./data/job-market.json','./manifest.json','./icon.svg','./career-options.css','./assets/hud/apple-touch-icon-dark-180.png'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE_ASSETS)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)));await self.clients.claim();})());});
async function networkFirst(request,fallbackPath=null){const cache=await caches.open(CACHE);try{const response=await fetch(request,{cache:'no-store',credentials:'same-origin',signal:(typeof AbortSignal!=='undefined'&&typeof AbortSignal.timeout==='function'?AbortSignal.timeout(4000):undefined)});if(!response.ok)return(await cache.match(request))||response;await cache.put(request,response.clone());return response;}catch{return(await cache.match(request))||(fallbackPath?await cache.match(fallbackPath):null)||new Response('Resource unavailable offline',{status:503,headers:{'Content-Type':'text/plain'}});}}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE),cached=await cache.match(request),refresh=fetch(request,{credentials:'same-origin'}).then(response=>{if(response?.ok)cache.put(request,response.clone());return response;}).catch(()=>null);return cached||(await refresh)||Response.error();}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(networkFirst(request,'./index.html'));return;}if(request.destination==='script'||request.destination==='style'||url.pathname.endsWith('/data/job-market.json')||url.pathname.endsWith('/data/tracker-audit.json')){event.respondWith(networkFirst(request));return;}event.respondWith(staleWhileRevalidate(request));});
self.addEventListener('message',event=>{if(event.data?.type!=='NOTIFY')return;const{title,body,tag}=event.data,iconUrl=new URL('./assets/hud/app-icon-192.png',self.registration.scope).href;event.waitUntil(self.registration.showNotification(title,{body,tag,icon:iconUrl,badge:iconUrl,requireInteraction:false}));});
