// Cert Tracker — dedicated visual dual-pillar learning-path workspace.
(function initLearningPathUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.topicEngine||!CT?.recommendations||!CT?.capabilityGates)return;const esc=CT.util.escapeHtml;
  const PHASES=Object.freeze({
    1:{title:'Foundations + current-role depth',sub:'Physical-security systems, networking fundamentals and infrastructure underneath the application'},
    2:{title:'Enterprise networking + network security',sub:'Professional routing, firewalls, segmentation and resilient systems'},
    3:{title:'Cloud + identity + SecOps + automation',sub:'Hybrid networking, identity, defensive operations and programmable integration'},
    4:{title:'OT + convergence engineering',sub:'Industrial systems, OT cybersecurity, integration and architecture foundations'},
    5:{title:'Security + convergence architecture',sub:'Design ownership, cloud/security architecture, commercial decisions and specialist depth'},
    6:{title:'Principal / professional capstone',sub:'Experience-gated expert recognition, leadership and architecture ownership'}
  });
  const GATE_AFTER=Object.freeze({1:'physicalSystemsEngineer',2:'networkSecurityEngineer',3:'otSecurityEngineer',4:'convergenceEngineer',5:'solutionsArchitect',6:'principalConvergenceArchitect'});

  function pathCerts(phase){
    const rows=CERTS.filter(c=>CT.store.effectivePhase(c)===phase&&state.myPath?.[c.id]);
    const routeRows=CT.focusedRoute?.enabled()?CT.focusedRoute.ordered(rows):rows;
    const next=CT.recommendations?.recommend?.({limit:1,horizon:'now'})?.[0]?.id;
    const ordered=[...routeRows].sort((a,b)=>(state.passes?.[a.id]?1:0)-(state.passes?.[b.id]?1:0));
    return next&&ordered.some(c=>c.id===next)?[ordered.find(c=>c.id===next),...ordered.filter(c=>c.id!==next)]:ordered;
  }
  function certItem(cert,nextId){
    const card=CT.careerFramework.scoreCard(cert),tandem=CT.recommendations.tandemProfile(card),cls=CT.focusedRoute?.enabled()?'LOCKED MILESTONE':CT.capabilityGates.portfolioClass(cert,card),done=!!state.passes?.[cert.id],blocked=(cert.deps||[]).filter(id=>!state.passes?.[id]),dot=done?'done':cert.id===nextId?'now':'';
    const depth=CT.dualPillarDepth?.certProfile?.(cert)?.depth;
    const detail=done?`Completed · ${cls}`:blocked.length?`Blocked by ${blocked.map(id=>CERTS.find(c=>c.id===id)?.code||id).join(', ')} · M${card.M}/K${card.K}`:`${cls} · M${card.M} market · K${card.K} capability · floor ${tandem.weaker}/10 · ${card.T}`;
    return `<div class="ct-learning-item${dot==='now'?' now':''}"><span class="ct-learning-dot ${dot}"></span><div><strong>${esc(cert.name)}</strong><small>${esc(detail)}${depth?` · ${depth.subjects} subjects / ${depth.deepCount} D4-D5`:''}</small></div></div>`;
  }
  function topicItem(row,nextTopicId){const now=row.topic.id===nextTopicId;return `<div class="ct-learning-item"><span class="ct-learning-dot ${now?'now':''}"></span><div><strong>${esc(row.topic.title)}</strong><small>${row.mastery}% evidenced · ${esc(row.reasons.slice(0,2).join(' · ')||row.topic.why)}</small></div></div>`;}
  function gateHtml(phase){if(CT.focusedRoute?.enabled()){const flow=CT.focusedRoute.definition.presentationFlow?.steps||[],step=flow.find(x=>x.kind==='CAREER_GATE'&&x.afterPhase===phase);if(!step)return'';return `<div class="ct-learning-gate ct-learning-career-gate"><div><strong>CAREER GATE · ${esc(step.verb)} · ${esc(step.title)}</strong><span>${esc(step.purpose)}</span></div><div><strong>NOT AN EXAM</strong><span>Advance on evidence + opportunity</span></div></div>`;}const key=GATE_AFTER[phase],gate=key?CT.capabilityGates.roleGateStatus(key):null;if(!gate)return'';return `<div class="ct-learning-gate"><div><strong>ROLE GATE · ${esc(gate.label)}</strong><span>${esc(gate.ready?'Market/capability transition gate met':'Practical evidence must catch up before treating this role transition as ready')}</span></div><div><strong>${gate.score}%${gate.ready?' ✓':''}</strong><span>${esc(gate.ready?'Gate met':gate.blockers.slice(0,1).join(''))}</span></div></div>`;}
  function focusCardCert(item){
    if(!item)return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next certification</div><h2>No available recommendation</h2><p>The current path has no unblocked certification recommendation.</p></div>`;
    const c=item.career,t=item.tandem||CT.recommendations.tandemProfile(c),depth=CT.dualPillarDepth?.certProfile?.(item.cert);
    return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next certification · dual-pillar</div><h2>${esc(item.name)}</h2><p>${esc(item.reasons.slice(0,3).join(' · '))}</p><div class="ct-learning-meta"><span class="ct-learning-chip">M${c.M} market access</span><span class="ct-learning-chip">K${c.K} capability</span><span class="ct-learning-chip">Floor ${esc(t.weaker)}/10</span><span class="ct-learning-chip">${esc(c.T)} timing</span><span class="ct-learning-chip">${item.readiness.score}% exam ready</span></div>${depth?`<div class="ct3-muted" style="margin-top:9px">Capability conversion target: ${esc(depth.completionStandard)}</div>`:''}</div>`;
  }
  function focusCardTopic(row,cert){if(!row)return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next capability task</div><h2>No topic gap detected</h2><p>Build practical evidence for the current phase rather than adding another badge automatically.</p></div>`;return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Build capability alongside ${esc(cert?.code||'the next cert')}</div><h2>${esc(row.topic.title)}</h2><p>${esc(row.topic.why)}</p><div class="ct-learning-meta"><span class="ct-learning-chip">${row.mastery}% evidenced</span><span class="ct-learning-chip">${row.certSynergy}% cert synergy</span><span class="ct-learning-chip">Phase ${row.phase}</span></div><div style="margin-top:12px">${row.topic.actions.slice(0,3).map(x=>`<div class="ct3-muted" style="margin-top:5px">→ ${esc(x)}</div>`).join('')}</div></div>`;}
  function focusTracksHtml(){
    const tracks=CT.focusedRoute?.definition?.focusTracks||[];if(!tracks.length)return'';
    const trackHtml=track=>`<div class="ct3-notice" style="margin-top:10px"><strong>${esc(track.title)} · ${esc(track.status)}</strong><div class="ct3-muted">${esc(track.why)}</div>${track.unlock?`<div class="ct3-muted" style="margin-top:7px"><strong>Unlock:</strong> ${esc(track.unlock.condition)}<br><strong>Evidence:</strong> ${esc(track.unlock.evidence)}</div>`:''}<div class="ct-learning-meta" style="margin-top:7px">${track.certs.map(id=>{const c=CERTS.find(x=>x.id===id);return `<span class="ct-learning-chip">${esc(c?.code||id)}</span>`;}).concat((track.topics||[]).map(id=>{const t=CT.topicEngine.TOPICS.find(x=>x.id===id);return `<span class="ct-learning-chip">${esc(t?.title||id)}</span>`;})).join('')}</div><div class="ct-learning-meta" style="margin-top:7px">${(track.resources||[]).map(row=>`<a class="ct3-link" href="${esc(row.url)}" target="_blank" rel="noopener noreferrer">${esc(row.label)}</a>`).join('')}</div></div>`;
    const visible=tracks.filter(track=>!track.hidden),hidden=tracks.filter(track=>track.hidden);
    return `<section class="ct3-card"><div class="ct3-title">Parallel depth tracks</div><div class="ct3-sub">Visible alongside the core path, but excluded from its milestone count and decisive recommendation queue. Activate a branch when current work, equipment or a target vacancy justifies it.</div>${visible.map(trackHtml).join('')}${hidden.length?`<details class="ct-learning-unlock-tracks" style="margin-top:14px"><summary style="cursor:pointer;min-height:44px">Employer-access unlock tracks · ${hidden.length}</summary><div class="ct3-sub" style="margin-top:8px">Collapsed by default so restricted vendor ecosystems do not bloat the core path. Open only when workplace access or responsibility makes the branch actionable.</div>${hidden.map(trackHtml).join('')}</details>`:''}</section>`;
  }
  function careerFlowHtml(){
    const flow=CT.focusedRoute?.definition?.presentationFlow;if(!flow)return'';
    return `<section class="ct3-card ct-career-flow"><div class="ct3-title">Career direction</div><div class="ct3-sub">${esc(flow.promise)}</div><div class="ct-career-flow-steps">${flow.steps.map(step=>`<div class="ct-career-flow-step ${step.kind==='CAREER_GATE'?'gate':'stage'}"><span>${esc(step.verb)}</span><strong>${esc(step.title)}</strong><small>${esc(step.purpose)}</small></div>`).join('')}</div><div class="ct3-muted" style="margin-top:10px">${esc(flow.tenSecondTest)}</div></section>`;
  }
  function render(){
    const nextCert=CT.recommendations.recommend({limit:1,horizon:'now'})[0]||null,nextTopic=CT.topicEngine.next({cert:nextCert?.cert||null}),nextId=nextCert?.id||'',nextTopicId=nextTopic?.topic.id||'';
    const phaseBlocks=[];for(let p=1;p<=6;p++){const spec=(CT.focusedRoute?.enabled()?CT.focusedRoute.definition.phases:PHASES)[p],certs=pathCerts(p),topics=CT.topicEngine.forPhase(p,{cert:nextCert?.cert||null,limit:5}),completed=certs.filter(c=>state.passes?.[c.id]).length;phaseBlocks.push(`<div class="ct-learning-phase"><div class="ct-learning-phase-label"><strong>P${p}</strong><span>${completed}/${certs.length} certs</span></div><div class="ct-learning-phase-body"><div class="ct-learning-phase-head"><div><div class="ct-learning-phase-title">${esc(spec.title)}</div><div class="ct-learning-phase-sub">${esc(spec.sub)}</div></div><div class="ct-learning-chip">${completed}/${certs.length} complete</div></div><div class="ct-learning-columns"><div class="ct-learning-cert-list"><div class="ct-learning-section-label">Certification / market-access ladder</div>${certs.length?certs.map(c=>certItem(c,nextId)).join(''):'<div class="ct3-muted">No certifications selected in this phase.</div>'}</div><div class="ct-learning-topic-list"><div class="ct-learning-section-label">Job-performance capability</div>${topics.length?topics.map(t=>topicItem(t,nextTopicId)).join(''):'<div class="ct3-muted">No active topic gaps for this phase.</div>'}</div></div></div></div>${gateHtml(p)}`);}
    const policy=CT.focusedRoute?.definition?.executionPolicy;
    return `<div class="ct-learning-workspace">${careerFlowHtml()}<div class="ct3-card"><div class="ct3-title">Evidence underneath the career path</div><div class="ct3-sub">Certifications, practical capability and ownership evidence support the direction above. They do not define it.</div></div><div class="ct-learning-hero">${focusCardCert(nextCert)}${focusCardTopic(nextTopic,nextCert?.cert)}</div><div class="ct3-notice"><strong>How to read this path:</strong> ${CT.focusedRoute?.enabled()?'Follow the career objective, not a badge queue. Work on the next useful milestone, but allow a strong ownership or design opportunity to outrank certification order. Supporting skills and optional focus tracks are not extra commitments.':'Certification order follows dependencies, balanced M/K value, timing, pathway relevance and evidence gaps.'} Passing the exam completes the credential checkpoint; the learning rung is only mature when the skill is labbed, used, designed or owned at the level appropriate to the role.</div>${policy?`<div class="ct3-notice"><strong>Attention policy:</strong> ${esc(policy.rule)}</div>`:''}<div class="ct-learning-roadmap">${phaseBlocks.join('')}</div>${focusTracksHtml()}</div>`;
  }
  function close(root){root?.remove();}
  function open(){const old=document.getElementById('ct-learning-overlay');if(old){old.remove();return;}const root=document.createElement('div');root.id='ct-learning-overlay';root.className='ct3-backdrop';root.innerHTML=`<section class="ct3-panel" style="width:min(1380px,100%);background:var(--surface);color:var(--text)" role="dialog" aria-modal="true" aria-label="Visual learning path"><div class="ct3-head"><div><div class="ct3-title">Learning Path</div><div class="ct3-sub">Market access and capability developed in tandem</div></div><button class="ct3-close" aria-label="Close">×</button></div><div class="ct3-body" style="max-height:82vh">${render()}</div></section>`;root.querySelector('.ct3-close').addEventListener('click',()=>close(root));root.addEventListener('mousedown',e=>{if(e.target===root)close(root);});document.body.appendChild(root);root.querySelector('.ct3-close').focus();}
  function init(){if(document.getElementById('ct-learning-launcher'))return;const b=document.createElement('button');b.id='ct-learning-launcher';b.type='button';b.textContent='Learning Path';b.setAttribute('aria-label','Open visual learning path');b.addEventListener('click',open);document.body.appendChild(b);CT.personalization?.organiseDock?.();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  CT.learningPath=Object.freeze({render,open,PHASES,GATE_AFTER,pathCerts});
})(window);
